import AppBar from "@/components/appbar";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: ["300", "400", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className} bg-white dark:bg-black`}>
        <AppBar />
        <div className="container mx-auto flex h-full w-full items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
